-- Give a message's own content type a place to live.
--
-- `BODYSTRUCTURE` says what a message's root MIME type is -- `multipart/mixed`,
-- `multipart/alternative`, `multipart/related`, or a single part's own type
-- for a message that is not multipart at all -- and `postio-imap` has it at
-- fetch time. Nothing kept it: `postio_app::reading::root_type` reconstructed
-- a plausible guess from the attachments and body a message happened to have,
-- which read a `multipart/related` (inline images) as `multipart/mixed`.
--
-- NULL rather than a guessed default: a row synced before this column existed
-- is honestly "not known" until the next resync fills it in, not "text/plain".
ALTER TABLE messages ADD COLUMN content_type TEXT;
