-- The index unified search orders by, when no account is named (#186).
--
-- `idx_messages_account_list` is `(account_id, received_at DESC, id DESC)`,
-- and a composite index can only supply `ORDER BY received_at DESC` while its
-- leading column is pinned to one value. `SearchRequest.account_id` used to
-- guarantee that unconditionally. It is now `AccountScope`, and
-- `AccountScope::Unified` names no account at all -- so from this migration on
-- there are queries with no `account_id` predicate, and without this index
-- SQLite has to scan the table and sort the whole match set in a temp b-tree
-- to satisfy the ordering.
--
-- That is not a small regression. Measured on four accounts of 30,000
-- messages each, on the broad-match recency path that `Plan::fetch_form`
-- takes past `RANK_BY_RELEVANCE_LIMIT` (ADR 0005 Q5a, #435):
--
--   account-scoped, on idx_messages_account_list      7.8 ms
--   unified, without this index                      20.3 s
--   unified, with it                                 18.8 ms
--
-- The cost is 2.2 MiB per 120,000 messages -- about 19 bytes a row, on rows
-- that already carry a subject, recipients and an FTS posting list -- and no
-- insert penalty measurable above the noise of the page cache. The same trade
-- `idx_messages_account_list` itself already makes.
--
-- `DESC` on both columns is load-bearing and not decoration: SQLite will walk
-- an ASC index backwards for a single-column `ORDER BY ... DESC`, but the
-- ordering here is on two columns and both must descend together, which an
-- ASC index cannot provide in one direction.
--
-- Not a replacement for idx_messages_account_list. A named account still
-- wants its own index: filtering to one account through this one would mean
-- reading every account's rows in date order and discarding most of them.

CREATE INDEX IF NOT EXISTS idx_messages_recency
    ON messages (received_at DESC, id DESC);
